# See the writing guide of rbs: https://github.com/ruby/rbs#guides
module STAC
  class Client
    def self.from_url: (String url) -> Client

    def initialize: (Catalog catalog) -> void

    attr_reader catalog: Catalog
  end
end
