# See the writing guide of rbs: https://github.com/ruby/rbs#guides
module STAC
  class Client
    def self.from_url: (String url, ?params: Hash[String, String], ?headers: Hash[String, String], **untyped) -> Client

    attr_reader catalog: Catalog
    attr_reader http_client: HTTPClient
    
    def initialize: (Catalog catalog, ?http_client: HTTPClient) -> void

    def request: (String url, ?method: untyped, ?params: Hash[String, untyped], ?headers: Hash[String, String]) -> Hash[String, untyped]
    def conformances: -> Array[String]
    def conforms_to?: (Regexp conformance) -> bool
  end
end
