module STAC
  class Client
    class HTTPClient
      DEFAULT_HEADERS: Hash[String, String]

      attr_reader connection: Faraday::Connection

      def initialize: (**untyped) -> void
                    
      def get: (URI::Generic | String url, ?params: Hash[String, String], ?headers: Hash[String, String]) -> Hash[String, untyped]
      def post: (URI::Generic | String url, ?params: Hash[String, String], ?headers: Hash[String, String]) -> Hash[String, untyped]
    end
  end
end
