module STAC
  class Client
    class ItemSearch
      DEFAULT_PARAMS: Hash[String, untyped]

      attr_reader client: Client
      
      @url: String
      @method: 'GET' | 'POST'
      @params: Hash[String, untyped]
      @headers: Hash[String, String]

      @pages: Enumerator[ItemCollection, void]

      def initialize: (
        client: Client,
        url: String,
        ?method: 'GET' | 'POST',
        ?params: Hash[Symbol, untyped],
        ?headers: Hash[String, String]
      ) -> void

      def items: -> Enumerator::Lazy[Item, void]
      def pages: -> Enumerator[ItemCollection, void]

      private

      def request!: -> Hash[String, untyped]
      def params_for_get: -> Hash[String, untyped]
      def params_for_post: -> Hash[String, untyped]
      def update_attrs!: (Link link) -> void
    end
  end
end
